- name: Install MySQL
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: Start MySQL
  ansible.builtin.systemd:
    name: mysqld
    state: started
    enabled: yes

- name: Set Password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1